#!/usr/bin/env python

import xmlrpclib
import getopt
import time
import sys

import pygtk
pygtk.require('2.0')
import gtk

KEY_EVENT_PRESS = (0)
KEY_EVENT_RELEASE = (1)

PULSE_HI = 1211
PULSE_LOW = 1183
PULSE_ARM = 1100

class ClientApp:

	def __init__(self):
		self.window = gtk.Window(gtk.WINDOW_TOPLEVEL)
		self.window.connect("key-press-event", self.key_event, KEY_EVENT_PRESS)
		self.window.connect("key-release-event", self.key_event, KEY_EVENT_RELEASE)
		self.window.show()

	def key_event(self, widget, event, direction):
		if direction == KEY_EVENT_PRESS:
			if event.keyval == gtk.keysyms.Escape:
				gtk.main_quit()
			elif event.keyval == gtk.keysyms.w:
				print "forward"
				self.forward()
			elif event.keyval == gtk.keysyms.s:
				print "back"
				self.back()
			elif event.keyval == gtk.keysyms.a:
				print "left"
				self.left()
			elif event.keyval == gtk.keysyms.d:
				print "right"
				self.right()
			elif event.keyval == gtk.keysyms._1:
				print "Arming channel 1, please wait..."
				self.arm(1)
				time.sleep(5)
			elif event.keyval == gtk.keysyms._2:
				print "Arming channel 2, please wait..."
				self.arm(2)
				time.sleep(5)
			elif event.keyval == gtk.keysyms._3:
				print "Arming channel 3, please wait..."
				self.arm(3)
				time.sleep(5)
		elif direction == KEY_EVENT_RELEASE:
			self.stop()
			print "stop"			
				

	def main(self):
		gtk.main()

class ClientProxy:
	
	def __init__(self, host):
		self.proxy = xmlrpclib.ServerProxy(host)

	def arm(self, channel):
		self.proxy.add_channel(channel)
		self.proxy.set_pulse(PULSE_ARM)

	def forward(self):
		self.proxy.set_pulse(1, PULSE_HI)
		self.proxy.set_pulse(2, PULSE_LOW)

	def back(self):
		self.proxy.set_pulse(1, PULSE_LOW)
		self.proxy.set_pulse(2, PULSE_LOW)

	def left(self):
		self.proxy.set_pulse(1, PULSE_LOW)
		self.proxy.set_pulse(2, PULSE_HI)
	
	def right(self):
		self.proxy.set_pulse(1, PULSE_HI)
		self.proxy.set_pulse(2, PULSE_LOW)

def usage():
    print """
Usage: %s [options]
Options:
    -r, --remote <uri> - Connect to remote server
    -h, --help - This help
""" % sys.argv[0]

if __name__ == '__main__':

    try:
        opts, args = getopt.getopt(sys.argv[1:], 'r:h', ['remote=', 'help'])
    except getopt.GetoptError, e:
        print str(e)
        usage()
        sys.exit(2)

    action = 'local'
    host = 'http://localhost:8000/'

    for o, a in opts:
        if o in ('-h', '--help'):
            usage()
            sys.exit(0)
        elif o in ('-r', '--remote'):
            action = 'remote'
            host = a

    proxy = ClientProxy(host)
    app = ClientApp()

    app.forward = proxy.forward
    app.back = proxy.back
    app.left = proxy.left
    app.right = proxy.right
    app.stop = proxy.stop
    app.arm = proxy.arm

    app.main()

