#!/usr/bin/env python

import xmlrpclib
import pygame
import getopt
import time
import sys

def getServoAngle(raw_angle):
        """Get an angle and calculate new duty cycle.
        """
        try:
                angle = int(raw_angle)
                if angle < 0 or angle > 180:
                        raise InputError
        except:
                return None
        match_value = 1100 + (angle*500/180)
        return match_value

def usage():
    print """
Usage: %s [options]
Options:
    -r, --remote <uri> - Connect to remote server
    -h, --help - This help
""" % sys.argv[0]

if __name__ == '__main__':

    try:
        opts, args = getopt.getopt(sys.argv[1:], 'r:h', ['remote=', 'help'])
    except getopt.GetoptError, e:
        print str(e)
        usage()
        sys.exit(2)

    action = 'local'
    host = 'http://localhost:8000/'

    for o, a in opts:
        if o in ('-h', '--help'):
            usage()
            sys.exit(0)
        elif o in ('-r', '--remote'):
            action = 'remote'
            host = a

    proxy = xmlrpclib.ServerProxy(host)

    pygame.init()
    pygame.display.set_mode((640,480),0)

	# Try to reduce some of the noise in the event queue
    pygame.event.set_allowed(None)
    pygame.event.set_allowed([pygame.QUIT, pygame.KEYDOWN, pygame.KEYUP])

    leftangle_HI = 36
    rightangle_HI = 36

    leftangle_LOW = 30
    rightangle_LOW = 30

    leftangle_ARM = 0
    rightangle_ARM = 0
    
    proxy.set_pulse(1, getServoAngle(leftangle_LOW))
    proxy.set_pulse(2, getServoAngle(rightangle_LOW))		

    while True:
        events = pygame.event.get()
        for event in events:
            if event.type == pygame.KEYDOWN:
                if event.key == pygame.K_w:
                    proxy.set_pulse(1, getServoAngle(leftangle_HI))
		    proxy.set_pulse(2, getServoAngle(rightangle_HI))		
                elif event.key == pygame.K_s:
                    proxy.set_pulse(1, getServoAngle(leftangle_LOW))
		    proxy.set_pulse(2, getServoAngle(rightangle_LOW))		
                elif event.key == pygame.K_a:
                    proxy.set_pulse(1, getServoAngle(leftangle_LOW))
		    proxy.set_pulse(2, getServoAngle(rightangle_HI))		
                elif event.key == pygame.K_d:
                    proxy.set_pulse(1, getServoAngle(leftangle_HI))
		    proxy.set_pulse(2, getServoAngle(rightangle_LOW))		
		elif event.key == pygame.K_i:
		    leftangle_HI += 1
		elif event.key == pygame.K_k:
		    if leftangle_HI > leftangle_LOW:
		        leftangle_HI -= 1
		elif event.key == pygame.K_o:
		    rightangle_HI += 1
		elif event.key == pygame.K_l:
		    if rightangle_HI > rightangle_HI:
		        rightangle_HI -= 1
		elif event.key == pygame.K_1:
		    proxy.set_pulse(1, getServoAngle(leftangle_ARM))
		    print "Please wait, Arming channel 1..."
                elif event.key == pygame.K_2:
		    proxy.set_pulse(2, getServoAngle(rightangle_ARM))
		    print "Please wait, Arming channel 2..."
                elif event.key == pygame.K_q:
                    sys.exit(0)

    sys.exit(0)

